### ISSUE TITLE
运行不了.报没有注册类

### ISSUE THREAD

**Issue by XGAGX** [aweiu/dm.dll#1]
return new winax.Object('dm.dmsoft');
               ^

Error: CreateInstance: dm.dmsoft 没有注册类

    at getDM (D:\xm\KSB\app\node_modules\dm.dll\dist\index.js:11:16)

**Comment by flajf** [comment]
大漠貌似是32位的，需要32位的node
https://github.com/durs/node-activex/issues/14#issuecomment-324115472

**Comment by aweiu** [comment]
@flajf 是的，文档里有写奥
