### ISSUE TITLE
666，感谢这位老大

### ISSUE THREAD

**Issue by flajf** [aweiu/dm.dll#2]
之前用清风的编辑器，不是很好用，就想自己用node去调dm.dll，什么都弄好了，
~~~
const ffi = require('ffi');
const path = `require('path');`
var libpath = path.join(__dirname, './dm.dll');
var dm = ffi.Library('libpath', {
    'MoveTo': ['int', 'int'],
});
dm.MoveTo(10,20)
console.log(dm)
~~~

就是报错
`Error: Dynamic Linking Error: Win32 error 126`
搞了好多天，百度不到解决办法，翻墙终于在掘金找到了这个成品，npm，分分钟就调通了，6啊，看代码去，感谢大佬

**Comment by aweiu** [comment]
[ffi](https://github.com/node-ffi/node-ffi) 适合调用普通的 c模块，dm.dll 是实现了 com 接口的 c模块。所以你那样行不通哈，得用 [winax](https://github.com/durs/node-activex)
