### ISSUE TITLE
electron 程序打包后，无法正确注册动态库

### ISSUE THREAD

**Issue by loverto** [aweiu/dm.dll#4]
electron 程序打包后，无法正确注册动态库

**Comment by eezouhong** [comment]
![image](https://user-images.githubusercontent.com/34080493/95289108-d4f81000-081e-11eb-9098-956dcf5eecce.png)

求大佬帮忙, 我electron引入winax  编译就报错, 装了electron-rebuild重新编译
 .\node_modules\.bin\electron-rebuild.cmd
但还是不行
一样的错误
 ERROR in ./node_modules/winax/activex.js
[0]     Module not found: Error: Can't resolve './build/Release/node_activex' in 'I:\yys-electron\node_modules\winax'

electron version:9.0.4
node version:14.13.0 32bit

**Comment by loverto** [comment]
用32位的nodejs

**Comment by eezouhong** [comment]
谢谢回答, 是32位的node,问题解决了, 我刚接触electron 不太熟悉, 要再main外层里引入dm, 不能再render层里引入
