### ISSUE TITLE
bindWindow 终止执行

### ISSUE THREAD

**Issue by mxl123** [aweiu/dm.dll#7]
你好，

我调用bindWindow时，代码直接停止执行了，看了下退出代码是 1073741819。我是用管理员权限打开cmd，然后node xxx.js运行的代码，其他类似查找窗口，键盘鼠标调用，暂时都没发现问题。

请问您知道这是什么问题怎么解决吗？

感谢！

**Comment by aweiu** [comment]
注意一下窗口绑定时候传入的各种参数指定的模式，不是所有窗口都适合后台绑定以及你指定的模式。
有些窗口在发生绑定模式不兼容的时候就会报错退出。

**Comment by mxl123** [comment]
好的，明白了，我多试试。感谢
